import CardAbout from "@/components/CardAbout";
import RepositoryList from "@/components/RepositoryList";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Github Repositories</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <nav className="navbar bg-dark">
          <div className="container">
            <span className="navbar-brand mb-0 h1 fw-bold text-white">
              Repo List
            </span>
          </div>
        </nav>
      </header>
      <main className="container my-3">
        <section>
          <h3>About User</h3>
          <CardAbout />
        </section>
        <section>
          <h3>Repository List</h3>
          <RepositoryList />
        </section>
      </main>
    </>
  );
}
